const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let modal=$("#modal"),preview=$("#preview"),page=1,kind="lesson";

function show(id){$$(".view").forEach(v=>v.classList.remove("active"));const v=$("#"+id);if(v)v.classList.add("active");$$("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id));const t=$("#title");if(t)t.textContent=id==="home"?"What shall we create today? ✨":(id==="admin"?"Creator & Admin":id.charAt(0).toUpperCase()+id.slice(1));}
function openGen(k,t){kind=k;$("#modalTitle").textContent={lesson:"Create a lesson",series:"Create a lesson series",sheet:"Create an activity sheet",workbook:"Create a workbook"}[k]||"Create a resource";if(t)$("#topic").value=t+" — English practice";page=1;showPage();modal.classList.add("show")}
function closeAll(){modal.classList.remove("show");preview.classList.remove("show")}
function showPage(){$$(".wizard-page").forEach(x=>x.classList.toggle("active",+x.dataset.page===page));$$(".step").forEach((x,i)=>x.classList.toggle("active",i===page-1));$("#pageLabel").textContent="Step "+page+" of 3";$("#back").style.visibility=page===1?"hidden":"visible";$("#next").hidden=page===3;$("#generate").hidden=page!==3}
$$("nav button").forEach(b=>b.onclick=()=>show(b.dataset.view));
document.addEventListener("click",e=>{const o=e.target.closest("[data-open]");if(o)openGen(o.dataset.open);const t=e.target.closest(".template");if(t)openGen("sheet",t.dataset.template)});
$("#closeGenerator").onclick=closeAll;$("#closePreview").onclick=closeAll;
$("#back").onclick=()=>{if(page>1){page--;showPage()}};$("#next").onclick=()=>{if(page<3){page++;showPage()}};
$$(".choice").forEach(b=>b.onclick=()=>b.classList.toggle("selected"));
$("#generate").onclick=()=>{const d={topic:$("#topic").value||"English Lesson",level:$("#level").value,duration:$("#duration").value,audience:$("#audience").value,skill:$("#skill").value,grammar:$("#grammar").value,vocab:$("#vocab").value,design:$("#design").value};$("#previewTitle").textContent=d.topic;$("#output").innerHTML=resource(d);modal.classList.remove("show");preview.classList.add("show")};
$("#print").onclick=()=>window.print();
function resource(d){const w=d.vocab.split(",").map(x=>x.trim()).filter(Boolean);return '<article class="paper"><div class="head"><span class="tag">'+esc(d.level)+'</span><span class="tag">'+esc(d.duration)+'</span><span class="tag">'+esc(d.audience)+'</span><h1>'+esc(d.topic)+'</h1><p>English • '+esc(d.skill)+' • '+esc(d.design)+'</p></div><h3>LEARNING OBJECTIVES</h3><p>Students will communicate about '+esc(d.topic.toLowerCase())+', use target vocabulary and complete a CEFR '+d.level+' task.</p><h3>1 · WARM-UP</h3><div class="task"><b>Think & Talk</b><p>What comes to mind when you think about '+esc(d.topic.toLowerCase())+'?</p><div class="answer"></div></div><h3>2 · VOCABULARY</h3><div class="task">'+w.map((x,i)=>(i+1)+'. '+esc(x)+' ____________').join("<br>")+'</div><h3>3 · LANGUAGE FOCUS</h3><div class="task"><b>'+esc(d.grammar)+'</b><p>Complete the sentences using the target language.</p><p>1. I ______________________________ before.</p><p>2. We ______________________________ last year.</p><p>3. She ______________________________ recently.</p></div><h3>4 · READING</h3><div class="task"><b>A memorable experience</b><p>Read the text and identify two important details and one new expression.</p><div class="answer"></div><div class="answer"></div></div><h3>5 · SPEAKING</h3><div class="task"><b>PAIR ROLE-PLAY</b><p>Ask: What happened? When was it? How did you feel? Would you do it again?</p><div class="answer"></div></div><h3>6 · EXIT TICKET</h3><div class="task">One new word: ____________________<br>One useful sentence: _______________<br>One question: ______________________</div><div class="key"><b>TEACHER ANSWER KEY</b><p>Review target vocabulary, grammar and speaking performance.</p></div></article>}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
showPage();